const Data =
  { 
    1: require('./../assets/images/search/1.png'), 
    2: require('./../assets/images/search/2.png'),
    3: require('./../assets/images/search/3.png'),
    4: require('./../assets/images/search/4.png'),
    5: require('./../assets/images/search/5.png'),
    6: require('./../assets/images/search/6.png'),
    7: require('./../assets/images/search/7.png'),
    8: require('./../assets/images/search/8.png'),
    9: require('./../assets/images/search/9.png'),
    10: require('./../assets/images/search/10.png'),
    11: require('./../assets/images/search/11.png'),
    12: require('./../assets/images/search/12.png'),
    13: require('./../assets/images/search/13.png'),
    14: require('./../assets/images/search/14.png'),
    15: require('./../assets/images/search/15.png'),
    16: require('./../assets/images/search/16.png'),
    17: require('./../assets/images/search/17.png'),
    18: require('./../assets/images/search/18.png'),
    19: require('./../assets/images/search/19.png'),
    20: require('./../assets/images/search/20.png'),
    21: require('./../assets/images/search/21.png'),
    22: require('./../assets/images/search/22.png'),
    23: require('./../assets/images/search/23.png'),
    24: require('./../assets/images/search/24.png'),
    25: require('./../assets/images/search/25.png'),
  }

export default Data